import java.awt.CardLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 341167849
 */
public class GuiFace extends javax.swing.JFrame {

    /**
     * Creates new form GuiFace
     */
    public GuiFace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        basePanel = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        loginText1 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        usernameLine = new javax.swing.JTextField();
        passwordLine = new javax.swing.JTextField();
        userameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        teacherRegistryButton = new javax.swing.JButton();
        tutorRegistryButton = new javax.swing.JButton();
        peerRegistryButton = new javax.swing.JButton();
        tutorRegistryPanel = new javax.swing.JPanel();
        tutorTitle = new javax.swing.JLabel();
        tutorBackButton = new javax.swing.JButton();
        tutorSignupButton = new javax.swing.JButton();
        tutorFirstNameField = new javax.swing.JTextField();
        tutorLastNameField = new javax.swing.JTextField();
        tutorFirstNameLabel = new javax.swing.JLabel();
        tutorLastNameLabel = new javax.swing.JLabel();
        tutorEmailLabel = new javax.swing.JLabel();
        tutorEmailField = new javax.swing.JTextField();
        tutorPhoneNumberLabel = new javax.swing.JLabel();
        tutorPhoneNumberField = new javax.swing.JTextField();
        tutorPasswordLabel = new javax.swing.JLabel();
        tutorPasswordField = new javax.swing.JTextField();
        tutorPassConfirmLabel = new javax.swing.JLabel();
        tutorPassConfirmField = new javax.swing.JTextField();
        peerRegistryPanel = new javax.swing.JPanel();
        peerTitle = new javax.swing.JLabel();
        peerBackButton = new javax.swing.JButton();
        teacherRegistryPanel = new javax.swing.JPanel();
        teacherTitle = new javax.swing.JLabel();
        teacherBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        basePanel.setLayout(new java.awt.CardLayout());

        loginText1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginText1.setText("Welcome to Peer Tutor Coordinator!");

        loginButton.setText("Login");

        userameLabel.setText("Username:");

        passwordLabel.setText("Password:");

        teacherRegistryButton.setText("Teacher Registry ");
        teacherRegistryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherRegistryButtonMouseClicked(evt);
            }
        });

        tutorRegistryButton.setText("Tutor Registry");
        tutorRegistryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutorRegistryButtonMouseClicked(evt);
            }
        });

        peerRegistryButton.setText("Peer Registry");
        peerRegistryButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peerRegistryButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(tutorRegistryButton)
                                .addGap(218, 218, 218)
                                .addComponent(peerRegistryButton))
                            .addComponent(passwordLine, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(teacherRegistryButton))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(loginText1))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(loginButton))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(usernameLine, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(userameLabel))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(passwordLabel)))
                        .addGap(0, 206, Short.MAX_VALUE)))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginText1)
                .addGap(68, 68, 68)
                .addComponent(userameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(loginButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherRegistryButton)
                    .addComponent(peerRegistryButton)
                    .addComponent(tutorRegistryButton))
                .addContainerGap())
        );

        basePanel.add(loginPanel, "loginPanel");

        tutorTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tutorTitle.setText("Become a tutor:");

        tutorBackButton.setText("Back");
        tutorBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tutorBackButtonMouseClicked(evt);
            }
        });

        tutorSignupButton.setText("Sign Up");

        tutorFirstNameLabel.setText("First Name:");

        tutorLastNameLabel.setText("Last Name:");

        tutorEmailLabel.setText("Email:");

        tutorPhoneNumberLabel.setText("Phone Number:");

        tutorPasswordLabel.setText("Password:");

        tutorPassConfirmLabel.setText("Confirm Password:");

        javax.swing.GroupLayout tutorRegistryPanelLayout = new javax.swing.GroupLayout(tutorRegistryPanel);
        tutorRegistryPanel.setLayout(tutorRegistryPanelLayout);
        tutorRegistryPanelLayout.setHorizontalGroup(
            tutorRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorRegistryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tutorRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tutorRegistryPanelLayout.createSequentialGroup()
                        .addGap(0, 725, Short.MAX_VALUE)
                        .addComponent(tutorBackButton)
                        .addGap(10, 10, 10))
                    .addGroup(tutorRegistryPanelLayout.createSequentialGroup()
                        .addGroup(tutorRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tutorRegistryPanelLayout.createSequentialGroup()
                                .addGroup(tutorRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tutorPasswordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tutorPhoneNumberLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(tutorEmailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tutorLastNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tutorFirstNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(tutorRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tutorLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tutorFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tutorEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tutorPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tutorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(tutorRegistryPanelLayout.createSequentialGroup()
                                .addComponent(tutorPassConfirmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tutorPassConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(tutorRegistryPanelLayout.createSequentialGroup()
                        .addGroup(tutorRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tutorTitle)
                            .addComponent(tutorSignupButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        tutorRegistryPanelLayout.setVerticalGroup(
            tutorRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorRegistryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tutorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tutorRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tutorFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tutorFirstNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tutorRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tutorLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tutorLastNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tutorRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tutorEmailLabel)
                    .addComponent(tutorEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tutorRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tutorPhoneNumberLabel)
                    .addComponent(tutorPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tutorRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tutorPasswordLabel)
                    .addComponent(tutorPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tutorRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tutorPassConfirmLabel)
                    .addComponent(tutorPassConfirmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(117, 117, 117)
                .addComponent(tutorSignupButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(tutorBackButton)
                .addContainerGap())
        );

        basePanel.add(tutorRegistryPanel, "tutorPanel");

        peerTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        peerTitle.setText("Become a peer:");

        peerBackButton.setText("Back");
        peerBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peerBackButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout peerRegistryPanelLayout = new javax.swing.GroupLayout(peerRegistryPanel);
        peerRegistryPanel.setLayout(peerRegistryPanelLayout);
        peerRegistryPanelLayout.setHorizontalGroup(
            peerRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peerRegistryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peerTitle)
                .addContainerGap(621, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, peerRegistryPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(peerBackButton)
                .addContainerGap())
        );
        peerRegistryPanelLayout.setVerticalGroup(
            peerRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peerRegistryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(peerTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, Short.MAX_VALUE)
                .addComponent(peerBackButton)
                .addContainerGap())
        );

        basePanel.add(peerRegistryPanel, "peerPanel");

        teacherTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        teacherTitle.setText("Become an admin:");

        teacherBackButton.setText("Back");
        teacherBackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherBackButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout teacherRegistryPanelLayout = new javax.swing.GroupLayout(teacherRegistryPanel);
        teacherRegistryPanel.setLayout(teacherRegistryPanelLayout);
        teacherRegistryPanelLayout.setHorizontalGroup(
            teacherRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherRegistryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherTitle)
                .addContainerGap(592, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacherRegistryPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(teacherBackButton)
                .addContainerGap())
        );
        teacherRegistryPanelLayout.setVerticalGroup(
            teacherRegistryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherRegistryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(teacherTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, Short.MAX_VALUE)
                .addComponent(teacherBackButton)
                .addContainerGap())
        );

        basePanel.add(teacherRegistryPanel, "teacherPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tutorBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorBackButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) basePanel.getLayout();
        card.show(basePanel, "loginPanel");//shows login screen panel
    }//GEN-LAST:event_tutorBackButtonMouseClicked

    private void peerBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peerBackButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) basePanel.getLayout();
        card.show(basePanel, "loginPanel");//shows login screen panel
    }//GEN-LAST:event_peerBackButtonMouseClicked

    private void teacherBackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherBackButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) basePanel.getLayout();
        card.show(basePanel, "loginPanel");//shows login screen panel
    }//GEN-LAST:event_teacherBackButtonMouseClicked

    private void teacherRegistryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherRegistryButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) basePanel.getLayout();
        card.show(basePanel, "teacherPanel");//shows login screen panel
    }//GEN-LAST:event_teacherRegistryButtonMouseClicked

    private void tutorRegistryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorRegistryButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) basePanel.getLayout();
        card.show(basePanel, "tutorPanel");
    }//GEN-LAST:event_tutorRegistryButtonMouseClicked

    private void peerRegistryButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peerRegistryButtonMouseClicked
        // TODO add your handling code here:
        CardLayout card = (CardLayout) basePanel.getLayout();
        card.show(basePanel,"peerPanel");
    }//GEN-LAST:event_peerRegistryButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiFace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel basePanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginText1;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordLine;
    private javax.swing.JButton peerBackButton;
    private javax.swing.JButton peerRegistryButton;
    private javax.swing.JPanel peerRegistryPanel;
    private javax.swing.JLabel peerTitle;
    private javax.swing.JButton teacherBackButton;
    private javax.swing.JButton teacherRegistryButton;
    private javax.swing.JPanel teacherRegistryPanel;
    private javax.swing.JLabel teacherTitle;
    private javax.swing.JButton tutorBackButton;
    private javax.swing.JTextField tutorEmailField;
    private javax.swing.JLabel tutorEmailLabel;
    private javax.swing.JTextField tutorFirstNameField;
    private javax.swing.JLabel tutorFirstNameLabel;
    private javax.swing.JTextField tutorLastNameField;
    private javax.swing.JLabel tutorLastNameLabel;
    private javax.swing.JTextField tutorPassConfirmField;
    private javax.swing.JLabel tutorPassConfirmLabel;
    private javax.swing.JTextField tutorPasswordField;
    private javax.swing.JLabel tutorPasswordLabel;
    private javax.swing.JTextField tutorPhoneNumberField;
    private javax.swing.JLabel tutorPhoneNumberLabel;
    private javax.swing.JButton tutorRegistryButton;
    private javax.swing.JPanel tutorRegistryPanel;
    private javax.swing.JButton tutorSignupButton;
    private javax.swing.JLabel tutorTitle;
    private javax.swing.JLabel userameLabel;
    private javax.swing.JTextField usernameLine;
    // End of variables declaration//GEN-END:variables
}
