/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 068682053
 */
public class InterFace extends javax.swing.JFrame {
    
    boolean subjectCheck = false;
    //.setVisible() = true;
    /**
     * Creates new form InterFace
     */
    public InterFace() {
        initComponents();
        subjectComboBox.removeAllItems();
        subjectComboBox.addItem("English");
        subjectComboBox.addItem("Math");
        subjectComboBox.addItem("Physics");
        subjectComboBox.addItem("Chemistry");
        subjectComboBox.addItem("Biology");
        subjectComboBox.addItem("French");
        subjectComboBox.addItem("Science");
        subjectComboBox.addItem("FI French");
        subjectComboBox.addItem("Other");
        grade9Button.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        main = new javax.swing.JTabbedPane();
        tutorRegistryPane = new javax.swing.JPanel();
        subjectComboBoxV2 = new javax.swing.JComboBox();
        confirmationButtonV2 = new javax.swing.JButton();
        grade11ButtonV2 = new javax.swing.JRadioButton();
        subjectLabelV2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        grade10ButtonV2 = new javax.swing.JRadioButton();
        availabilityLabel1 = new javax.swing.JLabel();
        mondayCheckV2 = new javax.swing.JRadioButton();
        period1CheckV2 = new javax.swing.JRadioButton();
        tesudayCheckV2 = new javax.swing.JRadioButton();
        period4CheckV2 = new javax.swing.JRadioButton();
        wednesdayCheckV2 = new javax.swing.JRadioButton();
        period2CheckV2 = new javax.swing.JRadioButton();
        thursdayCheckV2 = new javax.swing.JRadioButton();
        period3CheckV2 = new javax.swing.JRadioButton();
        fridayCheckV2 = new javax.swing.JRadioButton();
        period5CheckV2 = new javax.swing.JRadioButton();
        afterSchoolButtonV2 = new javax.swing.JRadioButton();
        signUpLabelV2 = new javax.swing.JLabel();
        grade9ButtonV2 = new javax.swing.JRadioButton();
        peerRegistryPane = new javax.swing.JPanel();
        signUpLabel = new javax.swing.JLabel();
        subjectComboBox = new javax.swing.JComboBox();
        subjectLabel = new javax.swing.JLabel();
        availabilityLabel = new javax.swing.JLabel();
        mondayCheck = new javax.swing.JRadioButton();
        tuesdayCheck = new javax.swing.JRadioButton();
        wednesdayCheck = new javax.swing.JRadioButton();
        thursdayCheck = new javax.swing.JRadioButton();
        fridayCheck = new javax.swing.JRadioButton();
        confirmationButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        period1Check = new javax.swing.JRadioButton();
        period4Check = new javax.swing.JRadioButton();
        period2Check = new javax.swing.JRadioButton();
        period3Check = new javax.swing.JRadioButton();
        period5Check = new javax.swing.JRadioButton();
        afterSchoolButton = new javax.swing.JRadioButton();
        grade9Button = new javax.swing.JRadioButton();
        grade11Button = new javax.swing.JRadioButton();
        grade10Button = new javax.swing.JRadioButton();
        loginPane = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        passwordField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subjectComboBoxV2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        confirmationButtonV2.setText("Confirm");

        grade11ButtonV2.setText("Grade 11");

        subjectLabelV2.setText("Subject to tutor:      ");

        jLabel2.setText("Periods available:");

        grade10ButtonV2.setText("Grade 10");

        availabilityLabel1.setText("Times available to tutor:");

        mondayCheckV2.setText("Monday");

        period1CheckV2.setText("Period 1");

        tesudayCheckV2.setText("Tuesday");

        period4CheckV2.setText("Period 4");

        wednesdayCheckV2.setText("Wednesday");

        period2CheckV2.setText("Period 2");

        thursdayCheckV2.setText("Thursday");

        period3CheckV2.setText("Period 3");

        fridayCheckV2.setText("Friday");

        period5CheckV2.setText("Period 5");

        afterSchoolButtonV2.setText("After School");

        signUpLabelV2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        signUpLabelV2.setText("Sign up");

        grade9ButtonV2.setText("Grade 9");

        javax.swing.GroupLayout tutorRegistryPaneLayout = new javax.swing.GroupLayout(tutorRegistryPane);
        tutorRegistryPane.setLayout(tutorRegistryPaneLayout);
        tutorRegistryPaneLayout.setHorizontalGroup(
            tutorRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorRegistryPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tutorRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signUpLabelV2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tutorRegistryPaneLayout.createSequentialGroup()
                        .addGroup(tutorRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subjectLabelV2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subjectComboBoxV2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(grade9ButtonV2)
                        .addGap(17, 17, 17)
                        .addComponent(grade10ButtonV2)
                        .addGap(18, 18, 18)
                        .addComponent(grade11ButtonV2))
                    .addComponent(availabilityLabel1)
                    .addComponent(confirmationButtonV2)
                    .addGroup(tutorRegistryPaneLayout.createSequentialGroup()
                        .addGroup(tutorRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tutorRegistryPaneLayout.createSequentialGroup()
                                .addComponent(mondayCheckV2)
                                .addGap(18, 18, 18)
                                .addComponent(tesudayCheckV2)
                                .addGap(18, 18, 18)
                                .addComponent(wednesdayCheckV2))
                            .addGroup(tutorRegistryPaneLayout.createSequentialGroup()
                                .addComponent(period1CheckV2)
                                .addGap(18, 18, 18)
                                .addComponent(period2CheckV2)
                                .addGap(18, 18, 18)
                                .addComponent(period3CheckV2)))
                        .addGap(18, 18, 18)
                        .addGroup(tutorRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(period4CheckV2)
                            .addGroup(tutorRegistryPaneLayout.createSequentialGroup()
                                .addComponent(thursdayCheckV2)
                                .addGap(18, 18, 18)
                                .addGroup(tutorRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(period5CheckV2)
                                    .addComponent(fridayCheckV2))))
                        .addGap(18, 18, 18)
                        .addComponent(afterSchoolButtonV2))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(527, Short.MAX_VALUE))
        );
        tutorRegistryPaneLayout.setVerticalGroup(
            tutorRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tutorRegistryPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(signUpLabelV2)
                .addGap(18, 18, 18)
                .addComponent(subjectLabelV2)
                .addGap(3, 3, 3)
                .addGroup(tutorRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectComboBoxV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grade9ButtonV2)
                    .addComponent(grade11ButtonV2)
                    .addComponent(grade10ButtonV2))
                .addGap(18, 18, 18)
                .addComponent(availabilityLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tutorRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mondayCheckV2)
                    .addComponent(tesudayCheckV2)
                    .addComponent(wednesdayCheckV2)
                    .addComponent(thursdayCheckV2)
                    .addComponent(fridayCheckV2))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tutorRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(period1CheckV2)
                    .addComponent(period2CheckV2)
                    .addComponent(period3CheckV2)
                    .addComponent(period4CheckV2)
                    .addComponent(period5CheckV2)
                    .addComponent(afterSchoolButtonV2))
                .addGap(18, 18, 18)
                .addComponent(confirmationButtonV2)
                .addContainerGap(450, Short.MAX_VALUE))
        );

        main.addTab("Become a Tutor", tutorRegistryPane);

        signUpLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        signUpLabel.setText("Sign up");

        subjectComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        subjectLabel.setText("Subject to be taught:");

        availabilityLabel.setText("Times available to be tutored:");

        mondayCheck.setText("Monday");

        tuesdayCheck.setText("Tuesday");

        wednesdayCheck.setText("Wednesday");

        thursdayCheck.setText("Thursday");

        fridayCheck.setText("Friday");

        confirmationButton.setText("Confirm");

        jLabel1.setText("Periods available:");

        period1Check.setText("Period 1");

        period4Check.setText("Period 4");

        period2Check.setText("Period 2");

        period3Check.setText("Period 3");

        period5Check.setText("Period 5");

        afterSchoolButton.setText("After School");

        grade9Button.setText("Grade 9");

        grade11Button.setText("Grade 11");

        grade10Button.setText("Grade 10");

        javax.swing.GroupLayout peerRegistryPaneLayout = new javax.swing.GroupLayout(peerRegistryPane);
        peerRegistryPane.setLayout(peerRegistryPaneLayout);
        peerRegistryPaneLayout.setHorizontalGroup(
            peerRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peerRegistryPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(peerRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(peerRegistryPaneLayout.createSequentialGroup()
                        .addGroup(peerRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(subjectLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(subjectComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(grade9Button)
                        .addGap(17, 17, 17)
                        .addComponent(grade10Button)
                        .addGap(18, 18, 18)
                        .addComponent(grade11Button))
                    .addComponent(availabilityLabel)
                    .addComponent(confirmationButton)
                    .addGroup(peerRegistryPaneLayout.createSequentialGroup()
                        .addGroup(peerRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(peerRegistryPaneLayout.createSequentialGroup()
                                .addComponent(mondayCheck)
                                .addGap(18, 18, 18)
                                .addComponent(tuesdayCheck)
                                .addGap(18, 18, 18)
                                .addComponent(wednesdayCheck))
                            .addGroup(peerRegistryPaneLayout.createSequentialGroup()
                                .addComponent(period1Check)
                                .addGap(18, 18, 18)
                                .addComponent(period2Check)
                                .addGap(18, 18, 18)
                                .addComponent(period3Check)))
                        .addGap(18, 18, 18)
                        .addGroup(peerRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(period4Check)
                            .addGroup(peerRegistryPaneLayout.createSequentialGroup()
                                .addComponent(thursdayCheck)
                                .addGap(18, 18, 18)
                                .addGroup(peerRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(period5Check)
                                    .addComponent(fridayCheck))))
                        .addGap(18, 18, 18)
                        .addComponent(afterSchoolButton))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(527, Short.MAX_VALUE))
        );
        peerRegistryPaneLayout.setVerticalGroup(
            peerRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peerRegistryPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(signUpLabel)
                .addGap(18, 18, 18)
                .addComponent(subjectLabel)
                .addGap(3, 3, 3)
                .addGroup(peerRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grade9Button)
                    .addComponent(grade11Button)
                    .addComponent(grade10Button))
                .addGap(18, 18, 18)
                .addComponent(availabilityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(peerRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mondayCheck)
                    .addComponent(tuesdayCheck)
                    .addComponent(wednesdayCheck)
                    .addComponent(thursdayCheck)
                    .addComponent(fridayCheck))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(peerRegistryPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(period1Check)
                    .addComponent(period2Check)
                    .addComponent(period3Check)
                    .addComponent(period4Check)
                    .addComponent(period5Check)
                    .addComponent(afterSchoolButton))
                .addGap(18, 18, 18)
                .addComponent(confirmationButton)
                .addContainerGap(450, Short.MAX_VALUE))
        );

        main.addTab("Become a Peer", peerRegistryPane);

        loginLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        loginLabel.setText("Login");

        loginButton.setText("Login");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        usernameLabel.setText("Username:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(loginButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(usernameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addGap(0, 166, Short.MAX_VALUE))
        );

        passwordLabel.setText("Password:");

        javax.swing.GroupLayout loginPaneLayout = new javax.swing.GroupLayout(loginPane);
        loginPane.setLayout(loginPaneLayout);
        loginPaneLayout.setHorizontalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPaneLayout.createSequentialGroup()
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPaneLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(passwordLabel)
                        .addGap(18, 18, 18)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(856, Short.MAX_VALUE))
        );
        loginPaneLayout.setVerticalGroup(
            loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginLabel)
                .addGap(62, 62, 62)
                .addGroup(loginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        main.addTab("Find a Tutor", loginPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterFace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterFace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton afterSchoolButton;
    private javax.swing.JRadioButton afterSchoolButtonV2;
    private javax.swing.JLabel availabilityLabel;
    private javax.swing.JLabel availabilityLabel1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton confirmationButton;
    private javax.swing.JButton confirmationButtonV2;
    private javax.swing.JRadioButton fridayCheck;
    private javax.swing.JRadioButton fridayCheckV2;
    private javax.swing.JRadioButton grade10Button;
    private javax.swing.JRadioButton grade10ButtonV2;
    private javax.swing.JRadioButton grade11Button;
    private javax.swing.JRadioButton grade11ButtonV2;
    private javax.swing.JRadioButton grade9Button;
    private javax.swing.JRadioButton grade9ButtonV2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPane;
    private javax.swing.JTabbedPane main;
    private javax.swing.JRadioButton mondayCheck;
    private javax.swing.JRadioButton mondayCheckV2;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel peerRegistryPane;
    private javax.swing.JRadioButton period1Check;
    private javax.swing.JRadioButton period1CheckV2;
    private javax.swing.JRadioButton period2Check;
    private javax.swing.JRadioButton period2CheckV2;
    private javax.swing.JRadioButton period3Check;
    private javax.swing.JRadioButton period3CheckV2;
    private javax.swing.JRadioButton period4Check;
    private javax.swing.JRadioButton period4CheckV2;
    private javax.swing.JRadioButton period5Check;
    private javax.swing.JRadioButton period5CheckV2;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JLabel signUpLabelV2;
    private javax.swing.JComboBox subjectComboBox;
    private javax.swing.JComboBox subjectComboBoxV2;
    private javax.swing.JLabel subjectLabel;
    private javax.swing.JLabel subjectLabelV2;
    private javax.swing.JRadioButton tesudayCheckV2;
    private javax.swing.JRadioButton thursdayCheck;
    private javax.swing.JRadioButton thursdayCheckV2;
    private javax.swing.JRadioButton tuesdayCheck;
    private javax.swing.JPanel tutorRegistryPane;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JRadioButton wednesdayCheck;
    private javax.swing.JRadioButton wednesdayCheckV2;
    // End of variables declaration//GEN-END:variables
}
